### ISSUE TITLE
Switching to different page floods log with errors

### ISSUE THREAD

**Issue by Mcpoowl** [appronto/-Slide-In-Slide-Out-widget#3]
Hi guys,

We've been using the widget for quite some time, and noticed that everything works fine on the page where the widget is set.
However, when we navigate to another page, the log is flooded with errors. The widget still works, but still, seems like something is not updated correctly or something.

Would be great if this could be fixed. 

PS. there's also default logging enabled which logs the HTML string everytime the widget is updated. You might want to turn that off aswell :-)

Thanks!

![image](https://cloud.githubusercontent.com/assets/2244753/23950040/f4d524e0-0989-11e7-9179-cbd34b4eca7a.png)

**Comment by joelvdgraaf** [comment]
New version 1.2.0 has been released in the appstore containing the fix for this issue!
