### ISSUE TITLE
Leaving the page where the widget is shown, causes Javascript engine to crash.

### ISSUE THREAD

**Issue by heuvelb** [appronto/-Slide-In-Slide-Out-widget#6]
Hi Joël,

I just spoke with Pim about the widget and he advised me to create an issue for the Slide Out (context) widget.
The issue I'm facing is this:
- A user is on a page with different input fields. the widget is used here to get information about previously submitted data (screenshot_1)
- Data in the widget is retrieved over association (Screenshot_2 and 3)
- When the user is done with his work on this page, he submits the data, the page is closed and the next page is shown (Screenshot_4)
- On the page that is shown now, the widget is not present.  (Screenshot_5)
- Clicking the button "Versturen" triggers a microflow that handles all the logic needed to process the data. Whilst this is running, the user sees a progress indicator. (screenshot_6)
This indicator is running forever, since something breaks the javascript. It looks like the widget is not unloaded. I have some errors in the Chrome console (screenshot_7)

Hopefully this provides some info, if I can be of service by showing the issue real-time with Skype, feel free to contact me (bart.van.den.heuvel@enexis.nl)

Edit: I've created a quick demo project to demonstrate this behaviour. 
Steps to reproduce the issue:
- Create a new project --> Save
- Edit the project and whilst in the Project dataview create a new Task.
- Open the Slide out pane
- Click cancel on the project page.

A dirty fix is done by myself by editing the buildstring function starting at line 219 in SlideOutContext.js. 
```
_buildString: function (callback) {
            logger.debug(this.id + "._buildString");
            var str = this.buttonString,
                settings = null,
                attr = null;

            for (attr in this.replaceattributes) {
                settings = this.replaceattributes[attr];
                str = str.split("${" + settings.variable + "}").join(settings.value);
            }

            console.log(this.id + "._buildString: " + str);
            if (this.slidebutton) {
                this.slidebutton.innerHTML = str;
                this._setButtonTop();

                if (callback && typeof callback === "function") {
                    logger.debug(this.id + "._renderString callback");
                    callback();
                }
            }
```

        }
![screenshot_1](https://user-images.githubusercontent.com/29229004/51532072-7834a600-1e3f-11e9-803b-d16425248279.png)
![screenshot_2](https://user-images.githubusercontent.com/29229004/51532073-78cd3c80-1e3f-11e9-81b4-513bc4640b8c.png)
![screenshot_3](https://user-images.githubusercontent.com/29229004/51532074-78cd3c80-1e3f-11e9-8149-1a6ffc3eef44.png)
![screenshot_4](https://user-images.githubusercontent.com/29229004/51532076-78cd3c80-1e3f-11e9-99ae-b640ae2f3da1.png)
![screenshot_5](https://user-images.githubusercontent.com/29229004/51532077-78cd3c80-1e3f-11e9-87a3-110003311b1d.png)
![screenshot_6](https://user-images.githubusercontent.com/29229004/51532079-78cd3c80-1e3f-11e9-8adf-a3a6499a5034.png)
![screenshot_7](https://user-images.githubusercontent.com/29229004/51532080-7965d300-1e3f-11e9-81df-ef15b3711c88.png)

[TestWidget.zip](https://github.com/appronto/-Slide-In-Slide-Out-widget/files/2782824/TestWidget.zip)

**Comment by joelvdgraaf** [comment]
The issue has to do, that the (Mendix) Javascript engine thinks that the previous widget still is alive and subscribed to that object an therefor each update is triggered.
I'm searching how to unscribe the widget properly by an destroy event of the widget.

**Comment by joelvdgraaf** [comment]
New version 1.2.0 has been released in the appstore containing the fix for this issue!
