### ISSUE TITLE
Mendix 8.0 Update

### ISSUE THREAD

**Issue by mpocta-gnw** [appronto/-Slide-In-Slide-Out-widget#7]
This widget no longer works with Mendix version 8.0 and above.  Our team would love to use this widget for our application but we need a version that works with Mendix version 8.0.

**Comment by mina1585** [comment]
Hi,
I got the same issue with mpocta-gnw. I'm using the widget for version 7 but it's not working on mendix 8. Is there any plan that you can upgrade this widget for Mendix 8?
Thanks,

**Comment by joelvdgraaf** [comment]
With the new 1.4.0 release in the [appstore:](https://appstore.home.mendix.com/link/app/17847/) is the issue been fixed and running with Mendix 8.1.1 and higher.
